### ISSUE TITLE
More then one Points on Google Maps

### ISSUE THREAD

**Issue by woutervdhorst** [laravel-frontend-presets/now-ui-dashboard#14]
I will use the Google maps in Dashboard.

Can you make a sample for a map with more then one marker points?
I have try in Demo.js maybe you can send me a update demo.js with more points on one map.

Then is my next step load markers from Mysql database.

Thanks

**Comment by teamupdivision** [comment]
Hello @woutervdhorst, thank you for using our products.
We'll consider your recommendation for our next release.
Have a great day!
