### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by SilverPaladin** [laravel-frontend-presets/now-ui-dashboard#16]
Fresh install of Laravel 6.18.0 on Homestead

Installed Now UI via composer require laravel-frontend-presets/now-ui-dashboard

Generating optimized autoload files
Deprecation Notice: Class LaravelFrontendPresets\NowUiPreset\NowUiPresetServiceProvider located in ./vendor/laravel-frontend-presets/now-ui-dashboard/src/NowUIPresetServiceProvider.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by teamupdivision** [comment]
Hello and thanks for using our products!
Please reinstall the project and try again, please follow the updated instructions from Github.

Thank you
