### ISSUE TITLE
php artisan ui nowui --auth fails invalid preset

### ISSUE THREAD

**Issue by SilverPaladin** [laravel-frontend-presets/now-ui-dashboard#20]
From readme: 

> 4. Run php artisan ui nowui command to install the NowUI preset. This will install all the necessary assets and also the custom auth views, it will also add the auth route in routes/web.php (NOTE: If you run this command several times, be sure to clean up the duplicate Auth entries in  routes/web.php)

$ php artisan ui nowui --auth

   InvalidArgumentException

  Invalid preset.

  at vendor/laravel/ui/src/UiCommand.php:41
    37|             return call_user_func(static::$macros[$this->argument('type')], $this);
    38|         }
    39|
    40|         if (! in_array($this->argument('type'), ['bootstrap', 'vue', 'react'])) {
  > 41|             throw new InvalidArgumentException('Invalid preset.');
    42|         }
    43|
    44|         $this->{$this->argument('type')}();
    45|

      +14 vendor frames
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by teamupdivision** [comment]
Hello, please follow the steps exactly in the order from the readme:
Please run first `composer require laravel/ui` before `php artisan ui nowui --auth`

Thank you
