### ISSUE TITLE
Deprecation Notice Laravel 7

### ISSUE THREAD

**Issue by jgrunder** [laravel-frontend-presets/now-ui-dashboard#24]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
  - Please note, issue was opened but for Laravel 6 and is now closed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Installation of UI

# Current Behavior

Deprecation Notice warning when generating optimized autoload files

# Failure Information (for bugs)

Deprecation Notice: Class LaravelFrontendPresets\NowUiPreset\NowUiPresetServiceProvider located in ./vendor/laravel-frontend-presets/now-ui-dashboard/src/NowUIPresetServiceProvider.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Fresh Laravel 7 installation
2. Install Now UI from composer
3. You'll have this warning when generating optimized autoload files

## Context

Fresh Laravel 7 install configured in Laravel Homestead environment (so all configuration PHP / NGinx etc. are correct)

* Device: Homestead
* Operating System: Homestead
* Browser and Version: NC

## Failure Logs

Deprecation Notice: Class LaravelFrontendPresets\NowUiPreset\NowUiPresetServiceProvider located in ./vendor/laravel-frontend-presets/now-ui-dashboard/src/NowUIPresetServiceProvider.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by teamupdivision** [comment]
Hello, thanks for using Creative Tim products.

Can you please check if renaming the file to **NowUiPresetServiceProvider.php** or renaming the class to **NowUiPreset\NowUIPresetServiceProvider** - it might be a problem related to case sensitiveness.

All the best

**Comment by jgrunder** [comment]
Hello,
I tried the first solution and it worked, I don't have a Deprecation Notice anymore. This confirms the case-sensitive problem in the filename or in the class, it's up to you to choose the best place to fix it :)

**Comment by teamupdivision** [comment]
thanks for your confirmation
