### ISSUE TITLE
Laravel 8.0 compatible

### ISSUE THREAD

**Issue by danieldhcode** [laravel-frontend-presets/now-ui-dashboard#26]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Installation of ui

# Current Behavior

Cant install cause cant work together with laravel 8.0

# Failure Information (for bugs)

See failure logs

## Steps to Reproduce

1. Fresh laravel 8 application
2. Install nowui from composer
3. you won't get here cause you cant install it.

## Context

* Device: local development system running ubuntu
* Operating System: ubuntu
* Browser and Version: nc

## Failure Logs

$ composer require laravel-frontend-presets/now-ui-dashboard
Using version ^1.0 for laravel-frontend-presets/now-ui-dashboard
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-frontend-presets/now-ui-dashboard v1.0.2 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
    - laravel-frontend-presets/now-ui-dashboard v1.0.3 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
    - Conclusion: don't install laravel/framework 7.x-dev
    - Conclusion: don't install laravel-frontend-presets/now-ui-dashboard v1.0.1
    - Conclusion: remove laravel/framework v8.3.0
    - Installation request for laravel-frontend-presets/now-ui-dashboard ^1.0 -> satisfiable by laravel-frontend-presets/now-ui-dashboard[v1.0.0, v1.0.1, v1.0.2, v1.0.3].
    - Conclusion: don't install laravel/framework v8.3.0
    - laravel-frontend-presets/now-ui-dashboard v1.0.0 requires laravel/framework ^5.5 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v8.3.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v8.3.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.3.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v8.3.0].
    - Installation request for laravel/framework (locked at v8.3.0, required as ^8.3) -> satisfiable by laravel/framework[v8.3.0].

**Comment by teamupdivision** [comment]
Hello and thank you for using Creative Tim products.

The product is not compatible with Laravel 8. We are working on an update which will be published a couple of days. 

Thanks

**Comment by teamupdivision** [comment]
Hello, the product is now compatible with Laravel 8.
