### ISSUE TITLE
Sidebar activepage 

### ISSUE THREAD

**Issue by Sirajunnasihin** [laravel-frontend-presets/now-ui-dashboard#30]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ √] I am running the latest version
- [ √] I checked the documentation and found no answer
- [ √] I checked to make sure that this issue has not already been filed
- [ √] I'm reporting the issue to the correct repository (for multi-repository projects)

# Failure Information (for bugs)

$activePage is undefined
Make the variable optional in the blade template. Replace {{ $activePage }} with {{ $activePage ?? '' }}

**Comment by Sirajunnasihin** [comment]
you need to replace {{ $activePage }} with {{ $activePage ?? '' }}

**Comment by teamupdivision** [comment]
Hi there, 

Thanks for reporting this issue and for using Creative Tim products.

If there is anything else we can help with or if you have any other issues, please let us know.

All the best,
Updivision Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
